// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVU1LYiEvdnbsCVRtz56LsU_EF-k4R0wg',
    appId: '1:824495606100:web:83c8d4fed9f33ff8a3a0c1',
    messagingSenderId: '824495606100',
    projectId: 'projet-upc1',
    authDomain: 'projet-upc1.firebaseapp.com',
    storageBucket: 'projet-upc1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBppzMIghCeLn_CKuYf8H-oo8RkqHsnmqE',
    appId: '1:824495606100:android:bc677a4546982096a3a0c1',
    messagingSenderId: '824495606100',
    projectId: 'projet-upc1',
    storageBucket: 'projet-upc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl5DKzFfLW0OVCunw5jlx8uLugbbHT-q8',
    appId: '1:824495606100:ios:2ca02cad98bd0f3fa3a0c1',
    messagingSenderId: '824495606100',
    projectId: 'projet-upc1',
    storageBucket: 'projet-upc1.firebasestorage.app',
    iosBundleId: 'com.example.projetUpc1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl5DKzFfLW0OVCunw5jlx8uLugbbHT-q8',
    appId: '1:824495606100:ios:2ca02cad98bd0f3fa3a0c1',
    messagingSenderId: '824495606100',
    projectId: 'projet-upc1',
    storageBucket: 'projet-upc1.firebasestorage.app',
    iosBundleId: 'com.example.projetUpc1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVU1LYiEvdnbsCVRtz56LsU_EF-k4R0wg',
    appId: '1:824495606100:web:887f9a5fe3dd6718a3a0c1',
    messagingSenderId: '824495606100',
    projectId: 'projet-upc1',
    authDomain: 'projet-upc1.firebaseapp.com',
    storageBucket: 'projet-upc1.firebasestorage.app',
  );
}
